name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 * * *"

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          - ROS_DISTRO: kinetic
            ROS_REPO: testing
            UPSTREAM_WORKSPACE: '.ci.rosinstall.kinetic'
            UPSTREAM_CMAKE_ARGS: '-DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.5m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.5m.so'
            ADDITIONAL_DEBS: 'python3-catkin-pkg-modules python3-rospkg-modules python3-numpy ros-kinetic-opencv3 python3-venv python3-empy python-catkin-tools'
            NOT_TEST_BUILD: true
          - ROS_DISTRO: kinetic
            ROS_REPO: main
            UPSTREAM_WORKSPACE: '.ci.rosinstall.kinetic'
            UPSTREAM_CMAKE_ARGS: '-DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.5m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.5m.so'
            ADDITIONAL_DEBS: 'python3-catkin-pkg-modules python3-rospkg-modules python3-numpy ros-kinetic-opencv3 python3-venv python3-empy python-catkin-tools'
            NOT_TEST_BUILD: true
          - ROS_DISTRO: melodic
            ROS_REPO: testing
            UPSTREAM_WORKSPACE: '.ci.rosinstall.melodic'
            UPSTREAM_CMAKE_ARGS: '-DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so'
            ADDITIONAL_DEBS: 'python3-catkin-pkg-modules python3-rospkg-modules python3-opencv python3-venv python3-empy python-catkin-tools'
            NOT_TEST_BUILD: true
          - ROS_DISTRO: melodic
            ROS_REPO: main
            UPSTREAM_WORKSPACE: '.ci.rosinstall.melodic'
            UPSTREAM_CMAKE_ARGS: '-DPYTHON_EXECUTABLE=/usr/bin/python3 -DPYTHON_INCLUDE_DIR=/usr/include/python3.6m -DPYTHON_LIBRARY=/usr/lib/x86_64-linux-gnu/libpython3.6m.so'
            ADDITIONAL_DEBS: 'python3-catkin-pkg-modules python3-rospkg-modules python3-opencv python3-venv python3-empy python-catkin-tools'
            NOT_TEST_BUILD: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
